name: Documentation

on:
  pull_request:
  push:
    branches: 
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/Documentation.yml'
    tags: 
      - '*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.10'
          arch: x64

      - name: "Copy readme to doc"
        run:
          cp ./README.md ./docs/src/index.md

      - name: "Install dependencies"
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: "Build and deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl